---
title: "Homework12"
author: "Nicole Phelan"
date: "2024-04-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Advanced ggplotting

```{r}
library(ggplot2)
library(dplyr)
```

In a grant proposal about hybridization between ferns Diplazium plantaginifolium and Diplazium ternatum, I want to include a plot of their overlapping elevation ranges. I want their ranges to be plotted on top of each other in different colors, and I want an intermediate color to display their shared elevation range.

```{r}
Species <- c("Diplazium plantaginifolium","Diplazium plantaginifolium","Diplazium ternatum","Diplazium ternatum")
El <- c(150,1600,500,2200) # lower and upper elevation bounds for each species
lab <- c("Species")
df <- data.frame(Species,El,lab)

p <- ggplot(data = df) +
  aes(x=lab,y=El,col=Species) +
  geom_segment(xend=lab, yend=1600, yend=2200,
               linewidth=15, 
               alpha=0.7)  +
  theme_classic(base_size = 20) +
  ylab("Elevation Range (m)") + 
  theme(axis.title.x=element_blank(),axis.text.x=element_blank())+
  scale_color_manual(values=c("darkgoldenrod1","darkturquoise"))
p
```

```{r}
sdata <- read.csv(file = "SampleDiplaziumData.csv")

```
