---
title: "Homework_3"
author: "Nicole Phelan"
date: "2024-01-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Question 1

#### Question:

```
First String    Second      1.22      3.4
Second          More Text   1.555555  2.2220
Third           x           3         124

First String,Second,1.22,3.4
Second,More Text,1.555555,2.2220
Third,x,3,124
```

#### Answer: 

```
FIND: \s{2,}

REPLACE: ,
```

**Explanation**: I extracted all places where there were two or more spaces and replaced those spaces with a comma.

# Question 2

#### Question:

```
Ballif, Bryan, University of Vermont
Ellison, Aaron, Harvard Forest
Record, Sydne, Bryn Mawr

Bryan Ballif (University of Vermont)
Aaron Ellison (Harvard Forest)
Sydne Record (Bryn Mawr)
```

#### Answer: 

```
FIND: (\w+), (\w+), (\w+ \w+ *\w*)

REPLACE: \2 \1 (\3)
```

**Explanation**: My FIND function matches each line of text. I used parenthesis to capture the first names, last names, and university names. The first commas and spaces were excluded from the parenthesis capture because they are consistent across lines, and I did not want them in my answer. The university names were captured following this formula: "word1" "space" "word2" "0 or more spaces" "0 or more word characters". This allowed me to capture university names that were 2 and 3 words long. My REPLACE function switches the order of the first (\2) and last name (\1) and places the university name (\3) in parenthesis.

# Question 3

#### Question:

```
0001 Georgia Horseshoe.mp3 0002 Billy In The Lowground.mp3 0003 Winder Slide.mp3 0004 Walking Cane.mp3

0001 Georgia Horseshoe.mp3
0002 Billy In The Lowground.mp3
0003 Winder Slide.mp3
0004 Walking Cane.mp3
```

#### Answer: 

```
FIND: (000\d* \w* \w* *\w* *\w*.mp3)

REPLACE: \1\n
```

**Explanation**: My FIND function matches what I want to be each line of text by starting with the track number and ending with .mp3. My FIND function also includes one space at the end outside of the parenthesis capture because I want to get rid of this space.

# Question 4

#### Question:

```
0001 Georgia Horseshoe.mp3
0002 Billy In The Lowground.mp3
0003 Winder Slide.mp3
0004 Walking Cane.mp3

Georgia Horseshoe_0001.mp3
Billy In The Lowground_0002.mp3
Winder Slide_0003.mp3
Walking Cane_0004.mp3
```

#### Answer: 

```
FIND: (000\d*) (\w* \w* *\w* *\w*)

REPLACE: \2_\1
```

**Explanation**: My FIND function captures the track number in one parenthesis capture and the song title in the second parenthesis capture. In my REPLACE function move the song title before the track number and separate them by an underscore.

# Question 5

#### Question:

```
Camponotus,pennsylvanicus,10.2,44
Camponotus,herculeanus,10.5,3
Myrmica,punctiventris,12.2,4
Lasius,neoniger,3.3,55

C_pennsylvanicus,44
C_herculeanus,3
M_punctiventris,4
L_neoniger,55
```

#### Answer: 

```
FIND: (\w)\w*,(\w*,)\d*.\d,(\d*)

REPLACE: \1_\2\3
```

**Explanation**: My FIND function includes the entire line and captures the first letter of the first word, the second word and its comma, and the final digit(s) after the last comma in the line. My REPLACE function only keeps what was captured in paranthesis and adds an underscore between the first letter of the first word and the first letter of the second word.

# Question 6

#### Question:

```
Camponotus,pennsylvanicus,10.2,44
Camponotus,herculeanus,10.5,3
Myrmica,punctiventris,12.2,4
Lasius,neoniger,3.3,55

C_penn,44
C_herc,3
M_punc,4
L_neon,55
```

#### Answer: 

```
FIND: (\w)\w*,(\w{4})\w*,\d*.\d,(\d*)

REPLACE: \1_\2,\3
```

**Explanation**: I edited my FIND from question 5 to only capture the first four letters of the second word. I added a second \w* after capturing the first four letters to capture the rest of the word. I also moved my comma to the outside of the capture. I kept my replace function the same, but I needed to add the comma after my second capture back.

# Question 7

#### Question:

```
Camponotus,pennsylvanicus,10.2,44
Camponotus,herculeanus,10.5,3
Myrmica,punctiventris,12.2,4
Lasius,neoniger,3.3,55

Campen, 44, 10.2
Camher, 3, 10.5
Myrpun, 4, 12.2
Lasneo, 55, 3.3
```

#### Answer: 

```
FIND: (\w{6})\w*,\w*,(\d*.\d),(\d*)

REPLACE: \1, \3, \2
```

**Explanation**: I edited my FIND from question 5 to only capture the first 6 letters of the first word. I took away the capture on my second word and I added a capture to the first number in the data set. Keeping only my captured words/numbers, I reordered them and added commas.